var Data =[
    {
        "id":"1",
        "Name":"Đức",
        "Age":"23",
        "School":"TBU",
    },
    {
        "id":"2",
        "Name":"Hoàng",
        "Age":"22",
        "School":"TLU",
    },
    {
        "id":"3",
        "Name":"Nam",
        "Age":"23",
        "School":"NEU",
    },
    {
        "id":"4",
        "Name":"Khánh",
        "Age":"23",
        "School":"TBU",
    },
    {
        "id":"5",
        "Name":"Phong",
        "Age":"23",
        "School":"NEU",
    },
    {
        "id":"6",
        "Name":"Định",
        "Age":"23",
        "School":"TLU",
    },
    {
        "id":"7",
        "Name":"Linh",
        "Age":"23",
        "School":"TBU",
    },
    {
        "id":"8",
        "Name":"Định",
        "Age":"23",
        "School":"TLU",
    },
    {
        "id":"9",
        "Name":"Linh",
        "Age":"23",
        "School":"TBU",
    },
];
module.exports = Data;